# Generated by Django 5.1 on 2024-09-02 09:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'size',
                    models.CharField(
                        choices=[
                            ('Tiny', 'Tiny'),
                            ('Small', 'Small'),
                            ('Medium', 'Medium'),
                            ('Large', 'Large'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'friendliness',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    'trainability',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    'shedding_amount',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    'exercise_needs',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('favorite_food', models.CharField(max_length=255)),
                ('favorite_toy', models.CharField(max_length=255)),
                (
                    'breed',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to='dog_api.breed'
                    ),
                ),
            ],
        ),
    ]
