# Generated by Django 5.1 on 2024-09-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_api', '0001_initial'),
        ('dog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='breed_api.breed'
            ),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
